name: Libraries

on:
  push:
    branches:
     - master

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: CLANG64
          install: >-
            mingw-w64-clang-x86_64-clang
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-ninja
      - name: Build
        run: |
          mkdir build
          cd build
          export CC=clang
          export CXX=clang++
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          ninja
      - name: Prepare output
        run: |
          mkdir output
          mv build/libcimguizmo.a output/libcimguizmo.a
          mv build/libimguizmo.a output/libimguizmo.a
      - name: 'Upload artifact to GitHub'
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: output
          retention-days: 1

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build git
          sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl-dev
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          ninja
      - name: Prepare output
        run: |
          mkdir output
          mv build/libcimguizmo.a output/libcimguizmo.a
          mv build/libimguizmo.a output/libimguizmo.a
      - name: 'Upload artifact to GitHub'
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: output
          retention-days: 1

  macOSamd64:
    name: MacOS (amd64)
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
      - name: Dependencies
        run: |
          rm /usr/local/bin/2to3
          rm /usr/local/bin/2to3-3.11
          rm /usr/local/bin/idle3
          rm /usr/local/bin/pydoc3
          rm /usr/local/bin/python3
          rm /usr/local/bin/python3-config
          brew install llvm ninja || true
          export CC=/usr/local/opt/llvm/bin/clang
          export CXX=/usr/local/opt/llvm/bin/clang++
          export PATH="/usr/local/opt/ninja/bin:$PATH"
          export LDFLAGS="-L/usr/local/opt/llvm/lib -L/usr/local/opt/llvm/lib/c++ -Wl,-rpath,/usr/local/opt/llvm/lib/c++"
          export CPPFLAGS="-I/usr/local/opt/llvm/include"
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          ninja
      - name: Prepare output
        run: |
          mkdir output
          mv build/libcimguizmo.a output/libcimguizmo.a
          mv build/libimguizmo.a output/libimguizmo.a
      - name: 'Upload artifact to GitHub'
        uses: actions/upload-artifact@v4
        with:
          name: macos-amd64
          path: output
          retention-days: 1
          
  macOSarm64:
    name: MacOS (arm64)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
      - name: Dependencies
        run: |
          rm /usr/local/bin/2to3
          rm /usr/local/bin/2to3-3.11
          rm /usr/local/bin/idle3
          rm /usr/local/bin/pydoc3
          rm /usr/local/bin/python3
          rm /usr/local/bin/python3-config
          brew install llvm ninja || true
          export CC=/usr/local/opt/llvm/bin/clang
          export CXX=/usr/local/opt/llvm/bin/clang++
          export PATH="/usr/local/opt/ninja/bin:$PATH"
          export LDFLAGS="-L/usr/local/opt/llvm/lib -L/usr/local/opt/llvm/lib/c++ -Wl,-rpath,/usr/local/opt/llvm/lib/c++"
          export CPPFLAGS="-I/usr/local/opt/llvm/include"
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          ninja
      - name: Prepare output
        run: |
          mkdir output
          mv build/libcimguizmo.a output/libcimguizmo.a
          mv build/libimguizmo.a output/libimguizmo.a
      - name: 'Upload artifact to GitHub'
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: output
          retention-days: 1

  updateGit:
    name: Update git
    runs-on: ubuntu-latest
    needs: [windows, linux, macOSamd64, macOSarm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
      - name: Download artifacts (Windows)
        uses: actions/download-artifact@v4
        with:
          name: windows
          path: downloads/windows
      - name: Download artifacts (Linux)
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: downloads/linux
      - name: Download artifacts (MacOS amd64)
        uses: actions/download-artifact@v4
        with:
          name: macos-amd64
          path: downloads/macos/amd64
      - name: Download artifacts (MacOS arm64)
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64
          path: downloads/macos/arm64
      - name: Detect cimguizmo changes
        id: cimguizmo-changes
        run: |
          git reset --hard
          git rev-parse HEAD:thirdparty/cimguizmo > dist/git/cimguizmo.txt
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Create dist folders
        run: |
          mkdir -p dist/windows
          mkdir -p dist/linux
          mkdir -p dist/macos/amd64
          mkdir -p dist/macos/arm64
      - name: Update cimguizmo
        if: steps.cimguizmo-changes.outputs.changed == 'true'
        run: |
          cp downloads/windows/libcimguizmo.a dist/windows/libcimguizmo.a
          cp downloads/windows/libimguizmo.a dist/windows/libimguizmo.a
          cp downloads/linux/libcimguizmo.a dist/linux/libcimguizmo.a
          cp downloads/linux/libimguizmo.a dist/linux/libimguizmo.a
          cp downloads/macos/amd64/libcimguizmo.a dist/macos/amd64/libcimguizmo.a
          cp downloads/macos/amd64/libimguizmo.a dist/macos/amd64/libimguizmo.a
          cp downloads/macos/arm64/libcimguizmo.a dist/macos/arm64/libcimguizmo.a
          cp downloads/macos/arm64/libimguizmo.a dist/macos/arm64/libimguizmo.a
      - name: Update commit tracking files
        run: |
          git rev-parse HEAD:thirdparty/cimguizmo > dist/git/cimguizmo.txt
      - name: Detect git changes
        id: git-changes
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit and push
        if: steps.git-changes.outputs.changed == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '<>'
          git add dist
          git commit -m "Updated static libraries"
          git push origin master